"""empty message

Revision ID: 66863b5378e7
Revises: 
Create Date: 2019-06-11 16:10:33.612667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66863b5378e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('password_digest', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('password_reset_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('admin_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state_province', sa.VARCHAR(length=255), nullable=True),
    sa.Column('street_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mobile_phone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('account_activation_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=255), nullable=True),
    sa.Column('privileges', sa.Integer(), nullable=True),
    sa.Column('shopperId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('customerId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('credit_balance', sa.Float(), nullable=True),
    sa.Column('min_balance', sa.Float(), nullable=True),
    sa.Column('ns1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns1_ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns2_ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns3_ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ns4_ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['privileges'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['status'], ['user_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_status')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
